Fix the detection for signature of linker::linkInModule()
The detector programs for the signature of llvm::linker::linkInModule()
always fail due to something similar as follow:

In file included from /usr/include/c++/6.2.1/memory:81:0,
                 from /usr/include/llvm/ADT/SmallVector.h:29,
                 from /usr/include/llvm/Support/Allocator.h:24,
                 from /usr/include/llvm/ADT/StringMap.h:18,
                 from /usr/include/llvm/Support/Host.h:17,
                 from /usr/include/llvm/ADT/Hashing.h:49,
                 from /usr/include/llvm/ADT/ArrayRef.h:13,
                 from /usr/include/llvm/Linker/IRMover.h:13,
                 from /usr/include/llvm/Linker/Linker.h:13,
                 from conftest.cpp:127:
/usr/include/c++/6.2.1/bits/unique_ptr.h: In instantiation of 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = llvm::Module]':
/usr/include/c++/6.2.1/bits/unique_ptr.h:236:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = llvm::Module; _Dp = std::default_delete<llvm::Module>]'
conftest.cpp:135:76:   required from here
/usr/include/c++/6.2.1/bits/unique_ptr.h:74:22: error: invalid application of 'sizeof' to incomplete type 'llvm::Module'
  static_assert(sizeof(_Tp)>0,
                      ^

The reason is that in those detector programs, the definition of
llvm::Module is not included. So include the definintion accordingly
make those detections really work for the signature.

Signed-off-by: Boqun Feng <boqun.feng@gmail.com>